import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"
import { ViteImageOptimizer } from "vite-plugin-image-optimizer"

// NOTE: sitemap.xml is generated by scripts/sitemap.cjs (URL + Google Images
// entries, data-derived lastmod) AFTER vite build — not by plugin.

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    ViteImageOptimizer({
      png: { quality: 80 },
      jpeg: { quality: 78 },
      jpg: { quality: 78 },
    }),
  ],
  server: {
    proxy: {
      "/api": "http://localhost:3000",
    },
  },
  // Production hygiene: strip console.* + debugger (Nav/Auth hot paths log
  // on every render; visitor consoles stay clean). Errors still propagate.
  esbuild: {
    drop: ["console", "debugger"],
  },
  build: {
    minify: "esbuild",
    manifest: true,
    chunkSizeWarningLimit: 1000,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes("node_modules")) {
            if (id.includes("react-router") || id.includes("/react/") || id.includes("react-dom") || id.includes("react-helmet")) return "react-vendor"
            if (id.includes("@reduxjs") || id.includes("react-redux")) return "redux"
            if (id.includes("gsap")) return "gsap"
            // NOTE: react-slick must NOT get its own chunk — splitting its CJS
            // default-export interop breaks ("type is invalid ... got: object"
            // on every /events/* route). It stays in "vendor".
            if (id.includes("appwrite") || id.includes("axios")) return "api"
            return "vendor"
          }
          return undefined
        },
      },
    },
  },
})
